### PR TITLE
bump to version 2.1.0

### PR DESCRIPTION
**Pull request by mr-deamon**
Updating files for DEB and RPM for version 2.0.1

### CODE REVIEW

**Comment by karlism** [comment]
@ants, can you please look into this? I've been running Patroni successfully built from this PR for more than a month now.

**Comment by mr-deamon** [comment]
As patroni 2.1.0 was released, i updated this repo. please consider building the packages with the changes, thanks!

**Comment by markwort** [comment]
Hey,

I am very glad that there are still some users of our packages!
However, since PostgreSQL.org provides a patroni package for most distributions (definitely more than we've covered), we think the logical step is to encourage people to switch to that package.

They package it a little bit differently - where this repo uses python virtualenv and combines all dependencies into a package, postgresql.org went the route of requiring all dependencies through other packages, in some cases even packaging those themselves as well.

@mr-deamon , @karlism please let us know how you feel about this. Is there any particular reason for preferring our package here?

I've already created a migration guide, I think the switch is quite straight-forward :)
https://github.com/cybertec-postgresql/patroni-packaging/blob/package_migration/package_migration.md

Feel free to add your comments on #11 !

**Comment by markwort** [comment]
@mmuehlbeyer I'm also interested in your opinion, I don't want to scatter this across too many different issues...
(In reference to #9 )

**Comment by karlism** [comment]
@markwort, thanks, I will give official patroni package a try and will update you on that

**Comment by karlism** [comment]
@markwort, I managed to upgrade all our Patroni clusters to official Postgres packages, thanks again, as I was not aware of PostgreSQL common repository. It is probably worth mentioning somewhere in `README.md` that this is legacy project and recommend using Patroni packages from PostgreSQL common repository.

**Comment by markwort** [comment]
Thank you for providing some feedback on my guide, I am glad it worked for you as well.

Since I got no further complaints, I've marked the repo as deprecated now, directly in the main README.md.
I know that the repository could be archived, I guess we'll give that a certain grace period stilll...

**Pull request closed without merging**
