### PR TITLE
Improve changing the version for RPMs

### PR DESCRIPTION
**Pull request by kustodian**
Now the version is only set in the spec file. Also when changing version we don't have to build the Docker image again, the same image will work with all versions.

### CODE REVIEW

**Comment by ants** [comment]
Can you uncomment patch0 and patch1 please?

**Comment by kustodian** [comment]
My bad. I was merging my changes and those were somehow automerged. I fixed it now and I also deleted those two patches that are not used.

**Comment by kustodian** [comment]
I also fixed that the `rpms` output dir was being created as root.

**Comment by ants** [comment]
Thanks for your contribution. I uploaded the latest build to releases.

**Pull request merged**
